services:
    ntopng:
        container_name: ntopng
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 3000:3000
        #volumes:
            # - /etc/ntopng.license:/etc/ntopng.license:ro
        depends_on:
            - clickhouse
            - netflow2ng
        command: [ '-i', 'tcp://10.0.1.3:5556', '-F', 'clickhouse;10.0.1.4;ntopng;ntopng;ntopng', '--redis', '10.0.1.5:6379:redispassword', '--community', "-m", "<your_local_subnet>" ]
        image: ntop/ntopng:latest
        restart: unless-stopped
        networks:
            ntop:
                ipv4_address: 10.0.1.2

    netflow2ng:
        container_name: netflow2ng
        ports:
            - 2055:2055/udp
        entrypoint: /netflow2ng # --level=debug
        image: synfinatic/netflow2ng
        restart: unless-stopped
        networks:
            ntop:
                ipv4_address: 10.0.1.3

    clickhouse:
        image: clickhouse/clickhouse-server:latest
        hostname: clickhouse
        container_name: clickhouse
        restart: unless-stopped
        environment:
            - CLICKHOUSE_USER=ntopng
            - CLICKHOUSE_PASSWORD=ntopng
            - CLICKHOUSE_DB=ntopng
        volumes:
            - /volume1/docker/ntop/clickhouse_data:/var/lib/clickhouse
            - ./volume1/docker/ntop/clickhouse_logs:/var/log/clickhouse-server
        networks:
            ntop:
                ipv4_address: 10.0.1.4

    redis:
        container_name: ntopng-redis
        volumes:
            - /volume1/docker/ntop/data:/data
        image: redis:6.2-alpine
        command: redis-server --appendonly yes --requirepass redispassword
        restart: always
        networks:
            ntop:
                ipv4_address: 10.0.1.5

networks:
    ntop:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.1.0/28
